# TASK 6: PYTHON (NUMPY) - innomatics research lab Internship

**By: Sahana Hegde**

In [1]:
#Question 1: Arrays
#Solution
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    arr.reverse()
    numpy_arr = numpy.array(arr,float)
    return numpy_arr

    
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [2]:
#Question 2: Shape and Reshape
#Solution
import numpy
change_array = numpy.array([1,2,3,4,5,6,7,8,9])
change_array.shape = (3, 3)
print (change_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
#Question 3: Transpose and Flatten
#Solution
import numpy
n, m = map(int, input().split())

storage = numpy.array([input().strip().split() for _ in range(n)], int)
print (storage.transpose())
print (storage.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [5]:
#Question concatenate
#Solution
import numpy

n,m,p=map(int,input().split())

lista1=[list(map(int,input().split())) for i in range(n)]
lista2=[list(map(int,input().split())) for i in range(m)]
a1=numpy.array(lista1)
a2=numpy.array(lista2)

print(numpy.concatenate((a1,a2),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [10]:
#Question 4: Zeroes and ones
#Solution
import numpy
size = tuple(map(int,input().strip().split()))
print( numpy.zeros(size, int) )
print( numpy.ones(size, int) )

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [12]:
#Question 5:Eye and identity
#Solution
import numpy
numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [13]:
#Question 6: Array mathematics
#Solution
import numpy
n,m = map(int,input().split())
a = numpy.array([input().split() for _ in range(n)],int)
b = numpy.array([input().split() for _ in range(n)],int)
print(a+b,a-b,a*b,a//b,a%b,a**b,sep="\n")

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [14]:
#Question 7:Floor,ceil,rint
#Solution

import numpy

numpy.set_printoptions(sign=' ')

array = numpy.array(input().split(),float)

print(numpy.floor(array))
print(numpy.ceil(array))
print(numpy.rint(array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [15]:
#Question 8: Sum and prod
#Solution
import numpy
N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)], int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

2 2 
1 2
3 4
24


In [16]:
#Question 9: Mean,var and std
#Solution
import numpy
a = numpy.array([input().split() for _ in range(int(input().split()[0]))],int)
print(numpy.mean(a,axis=1),numpy.var(a,axis=0),numpy.std(a),sep="\n")

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.118033988749895


In [25]:
#Question 10: Dot and cross
#Solution
import numpy
n = int(input())
u = numpy.array([input().split() for _ in range(n)], int)
v = numpy.array([input().split() for _ in range(n)], int)
print(numpy.dot(u, v))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [18]:
#Question 11: Inner and outer
#Solution
import numpy
A = numpy.array(input().split(), int)
B = numpy.array(input().split(), int)
print(numpy.inner(A, B), numpy.outer(A, B), sep='\n')

0 1
2 3
3
[[0 0]
 [2 3]]


In [19]:
#Question 13: Polynomials
#Solution
import numpy
print(numpy.polyval(numpy.array(input().split(),float),int(input())))

1.1 2 3
0
3.0


In [23]:
#Question 14:Linear algebra
#Solution
import numpy
array=[list(map(float,input().split())) for i in range(int(input()))]
print(round(numpy.linalg.det(array),2))

2
1.1 1.1
1.1 1.1
0.0
